basePath: /
info:
  contact: {}
  description: This is API for completing final project 3 hacktiv8
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Hacktiv8 KanbanBoard API
  version: "1.0"
paths: {}
swagger: "2.0"
